"""
Algorithms that can correctly predict stock prices can help generate millions of dollars. In this one-player game,
you try to predict the rise and fall of the stock price of various stocks and buy or sell the stocks accordingly.

You start with $100. Each turn you will be given the stock prices of current day and previous 4 days.
You must then choose to BUY or SELL the stocks. Your program will be run with input for 1 day at a time.

The stock prices are generated by us and may contain patterns.

## Input Format

The input of each turn will consist of multiple lines. All money values are doubles to two decimal places,
all other numbers are integers.

The first line contains three space separated numbers m k d.

m - the amount of money you could spend that day.
k - the number of different stocks available for buying or selling.
d - the number of remaining days for trading stocks.
k lines follow, each in the following format: name owned prices

name - the name of the stock (a string).
owned - the number of shares you own of that stock.
prices - 5 space separated numbers representing the stock's price for the last 5 days.
These are ordered from oldest to newest, so the last number is the current stock price.
Your program will be fed the days sequentially so you can write to a file in order to store a longer history of the prices.

## Output Format

The output for each turn should also contain multiple lines:

Output N for the number of transactions you wish to make. Output 0 if you are not making any transactions that day.

If you are making transactions, output N lines containing the name of the stock (case sensitive),
BUY or SELL, and the number of shares you wish to buy or sell.

NOTE: Money earned from selling stocks will only become available (for buying stocks) on the following day.

## Task

You trade until you run out of days. Any stocks left on the last day will automatically be sold at the last day's market price.
Your objective is to make as much money as possible starting from $100.

Complete the function printTransactions that takes a float m money left, an integer k number of stocks,
an integer d days left, a string array name of stock names, an integer array owned of stocks owned,
and an 2d integer array prices of stock prices containing k arrays of length 5 and print your output.

All indexes correspond properly (For index i, the name of the stock is name[i],
the number of shares of it you hold is owned[i] and the data about it is prices[i].

## Sample Case
1- 1203,49$ (si plus bas achète direct)
2- 1178.56$ - 52.6974 points. (mean reversion improvisé)
3. 110.28$ - 15.1434 points. (regarde la pente de la regression >0 + mean reversion)
"""
import sys, statistics


def linear_regression(x, y):
    n = len(x)
    mean_x = sum(x) / n
    mean_y = sum(y) / n
    cov_xy = sum((xi - mean_x) * (yi - mean_y) for xi, yi in zip(x, y))
    var_x = sum((xi - mean_x) ** 2 for xi in x)
    slope = cov_xy / var_x
    return slope


def printTransactions(m: float, k: int, d: int, name: list[str], owned: list[int], prices: list[list[float]]) \
        -> list[int | list[str, str, int]]:
    """
    All indexes must correspond properly (For index i, the name of the stock is name[i], the number of shares of it you hold
    is owned[i] and the data about it is prices[i]).
    :param m: money left.
    :param k: number of stocks.
    :param d: days left.
    :param name: stock names.
    :param owned: number of stocks owned for the appropriate stock.
    :param prices: stock prices containing ``k`` arrays of length 5.
    :return: Tuple of number of transaction to make and list of transactions
    containing the name, buy or sell and the number of it to buy or sell.
    """
    transactions = [0]
    buy: list[tuple[str, float, float]] = []  # index - price - pente
    days = [1, 2, 3, 4, 5]
    for s in range(k):
        actual = prices[s][-1]
        slope = linear_regression(days, prices[s])
        mean = statistics.mean(prices[s])
        print(f"{name[s]}: {slope=:.2f} {actual=} {mean=:.2f}  buyable:{int(m // actual)}")
        if slope > 0.1 and actual > mean and int(m // actual) > 0:
            buy.append((name[s], actual, slope))
        elif slope < -0.1 and owned[s] > 0:
            transactions.append((name[s], "SELL", owned[s]))
        elif actual == max(prices[s]) and owned[s] > 0:
            transactions.append((name[s], "SELL", owned[s] // 2))
    # trie pour acheté à la plus forte croissance
    buy.sort(key=lambda x: x[2], reverse=True)
    for b in buy:
        if int(m // b[1]) > 0:
            transactions.append([b[0], "BUY", int(m // b[1])])
            m %= b[1]
    transactions[0] = len(transactions) - 1
    return transactions


def displayTransactions(transactions: list[int | list[str, str, int]]) -> str:
    txt = str(transactions[0])
    if transactions[0] > 0:
        for t in transactions[1:]:
            txt += "\n"
            txt += f"{t[0]} {t[1]} {t[2]}"
    return txt


sys.stdin = open('Stock Predictions.txt')

data = sys.stdin.buffer.read().splitlines()
Mstr, Kstr, Dstr = data.pop(0).split()
M, K, D = float(Mstr), int(Kstr), int(Dstr)
name_lst, owned_lst, price_lst = [], [], []
for d in data:
    line = d.split()
    name_lst.append(str(line[0], 'utf-8'))
    owned_lst.append(int(line[1]))
    price_lst.append(list(map(float, line[2:])))

print(displayTransactions(printTransactions(M, K, D, name_lst, owned_lst, price_lst)))
